# https://taskfile.dev

version: '3'

vars:
  BUILD_DATE: $(date +%Y%m%d%H)

tasks:
  debian:
    desc: build debian image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/debian -t ysicing/debian:{{.BUILD_DATE}} -t ghcr.io/ysicing/debian -t ttl.sh/core/debian --push debian

  god:
    desc: build go debian image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/god -t ysicing/god:{{.BUILD_DATE}} -t ghcr.io/ysicing/god -t ttl.sh/core/god --push god

  registry:
    desc: build registry image
    cmds:
      - docker buildx build --pull --platform linux/amd64 -t ysicing/registry -t ysicing/registry:{{.BUILD_DATE}} -t ttl.sh/core/registry --push registry

  skopeo:
    desc: build skopeo image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/registry -t ysicing/skopeo:{{.BUILD_DATE}} -t ttl.sh/core/skopeo -t ghcr.io/ysicing/skopeo --push skopeo

  default:
    cmds:
      - task: debian
      - task: god
      - task: skopeo
