# https://taskfile.dev

version: '3'

vars:
  BUILD_DATE: $(date +%Y%m%d%H)

includes:
  all-debian:
    taskfile: ./debian/Taskfile.yml
    dir: ./debian

tasks:
  debian:
    desc: build debian image
    cmds:
      - task: all-debian
  god:
    desc: build go debian image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/god -t ysicing/god:{{.BUILD_DATE}} -t ghcr.io/ysicing/god --push god

  god-node:
    desc: build god-node debian image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/god-node -t ysicing/god-node:{{.BUILD_DATE}} -t ghcr.io/ysicing/god-node --push god-node

  goa:
    desc: build go alpine image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/goa -t ysicing/goa:{{.BUILD_DATE}} -t ghcr.io/ysicing/goa --push goa

  skopeo:
    desc: build skopeo image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/registry -t ysicing/skopeo:{{.BUILD_DATE}} -t ghcr.io/ysicing/skopeo --push skopeo

  r3m:
    desc: build r3m image
    cmds:
      - docker buildx build --pull --platform linux/amd64 -t ysicing/r3m -t ysicing/r3m:{{.BUILD_DATE}} -t ghcr.io/ysicing/r3m --push r3m

  node_exporter:
    desc: build node_exporter image
    cmds:
      - docker buildx build --pull --platform linux/amd64 -t ysicing/node_exporter -t ysicing/node_exporter:{{.BUILD_DATE}} -t ghcr.io/ysicing/node_exporter --push node_exporter

  caddy:
    desc: build caddy image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/caddy2 -t ysicing/caddy2:{{.BUILD_DATE}} -t ghcr.io/ysicing/caddy2 --push caddy

  postgres:
    desc: build postgres image with timescaledb and pgvector
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/postgres -t ysicing/postgres:{{.BUILD_DATE}} -t ghcr.io/ysicing/postgres --push postgres

  mariadb:
    desc: build mariadb image with optimized config
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/mariadb -t ysicing/mariadb:{{.BUILD_DATE}} -t ghcr.io/ysicing/mariadb --push mariadb

  default:
    cmds:
      - task: debian
      - task: god
      - task: skopeo
      - task: r3m
      - task: caddy
