name: Build Debian Docker Image

env:
  GO_VERSION: '1.21'
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '0 8 */1 * *'
  push:
    branches:
    - master
jobs:
  debian:
    name: build debian image
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: debian
        platforms: linux/amd64,linux/arm64
        push: true
        pull: true
        tags: hub.ysicing.net/library/debian
