FROM spanda/percona-xtrabackup:base

RUN curl -SL https://github.com/odise/go-cron/releases/download/v0.0.7/go-cron-linux.gz \
    | zcat > /usr/local/bin/go-cron \
  && chmod u+x /usr/local/bin/go-cron

ENV VERSION 201804191818

ADD entrypoint.sh /bin/entrypoint
ADD backup.sh /bin/backup

RUN chmod 755 /bin/entrypoint /bin/backup

ENTRYPOINT ["entrypoint"]