# https://taskfile.dev

version: '3'

vars:
  BUILD_DATE: $(date +%Y%m%d%H)

tasks:
  debian12:
    desc: build debian12 image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/debian:12 -t ysicing/debian:12-{{.BUILD_DATE}} --push 12

  debian13:
    desc: build debian13 image
    cmds:
      - docker buildx build --pull --platform linux/amd64,linux/arm64 -t ysicing/debian:13 -t ysicing/debian:13-{{.BUILD_DATE}} -t ysicing/debian -t ghcr.io/ysicing/debian -t ghcr.io/ysicing/debian:13 --push 13

  default:
    desc: build all debian images
    cmds:
      - task: debian13
      - task: debian12
