name: Build Docker Image
on:
  push:
  schedule:
    - cron: '0 4 */1 * *'
jobs:
  build:
    name: build sdk docker image
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build docker image
      run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          set -x
          ./build.sh
          docker logout
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}