name: Build Docker Image

env:
  GO_VERSION: '1.21'
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
    - master
jobs:
  god:
    name: build god image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
    - name: install task
      run: |
        echo "install task"
        go install github.com/go-task/task/v3/cmd/task@latest
    - name: build god image
      run: |
          task god
    - name: Trivy vulnerability scanner god
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/god'
        format: 'github'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
  debian:
    name: build debian image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
    - name: install task
      run: |
        echo "install task"
        go install github.com/go-task/task/v3/cmd/task@latest
    - name: build debian image
      run: |
          task debian
    - name: Trivy vulnerability scanner debian
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/debian'
        format: 'github'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
