name: Build GoA

env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '30 12 * * 5'
  push:
    paths:
    - 'goa/*'
    branches:
    - master
jobs:
  build:
    name: build goa image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
    - name: install task
      run: |
        echo "install task"
        go install github.com/go-task/task/v3/cmd/task@latest
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Goa
      run: |
        task goa
    - name: Trivy vulnerability scanner goa
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/goa'
        format: 'github'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

