name: Build God

env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
    - master
jobs:
  build:
    name: build god image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build God
      uses: docker/build-push-action@v6
      with:
        context: god
        platforms: linux/amd64,linux/arm64
        push: true
        pull: true
        tags: |
          ghcr.io/ysicing/god
          ysicing/god
          ttl.sh/ysicing/god
    - name: Trivy vulnerability scanner god
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/god'
        format: 'github'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

