name: Build R3M

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 8 * * 6'
  push:
    paths:
    - 'r3m/**'
    - '.github/workflows/r3m.yml'
    branches:
    - master
jobs:
  build:
    name: build r3m image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build r3m
      uses: docker/build-push-action@v6
      with:
        context: r3m
        platforms: linux/amd64,linux/arm64
        push: true
        pull: true
        tags: |
          ghcr.io/ysicing/r3m
          ysicing/r3m
          ttl.sh/ysicing/r3m
    - name: Trivy vulnerability scanner r3m
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/r3m'
        format: 'github'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
