name: Build Skopeo

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 8 * * 6'
  push:
    paths:
    - 'skopeo/**'
    - '.github/workflows/skopeo.yml'
    branches:
    - master
jobs:
  build:
    name: build skopeo image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build skopeo
      uses: docker/build-push-action@v6
      with:
        context: skopeo
        platforms: linux/amd64,linux/arm64
        push: true
        pull: true
        tags: |
          ghcr.io/ysicing/skopeo
          ysicing/skopeo
          ttl.sh/ysicing/skopeo
    - name: Trivy vulnerability scanner skopeo
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/skopeo'
        format: 'github'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
